const links = "http://hangaroundtheweb.com/2018/07/cognitive-dissonance-in-programming/"+
"https://news.ycombinator.com/item?id=17660011"+
"https://www.youtube.com/watch?v=Qj1FK8n7WgY&feature=youtu.be"+
"https://blog.datawrapper.de/colorguide/"+
"https://www.styleurl.app/"+
"https://zen-of-programming.com/kickass-portfolio/"+
"https://www.nytimes.com/2018/07/25/well/how-not-to-let-your-phone-ruin-your-vacation.html?utm_source=Blog+Newsletter&utm_campaign=e95f1f66c9-EMAIL_CAMPAIGN_2018_08_01_04_38&utm_medium=email&utm_term=0_6e017e2559-e95f1f66c9-48191967"+
"https://www.outsideonline.com/2327746/equation-will-make-you-better-everything-stress-rest-growth?utm_source=Blog+Newsletter&utm_campaign=e95f1f66c9-EMAIL_CAMPAIGN_2018_08_01_04_38&utm_medium=email&utm_term=0_6e017e2559-e95f1f66c9-48191967"+
"https://www.bakadesuyo.com/2018/07/perfectionism/?utm_source=Blog+Newsletter&utm_campaign=e95f1f66c9-EMAIL_CAMPAIGN_2018_08_01_04_38&utm_medium=email&utm_term=0_6e017e2559-e95f1f66c9-48191967"+
"https://blog.rescuetime.com/goal-setting-mental-biases/?utm_source=Blog+Newsletter&utm_campaign=e95f1f66c9-EMAIL_CAMPAIGN_2018_08_01_04_38&utm_medium=email&utm_term=0_6e017e2559-e95f1f66c9-48191967"+
"https://www.rescuetime.com/guides/gmail?utm_source=Blog+Newsletter&utm_campaign=e95f1f66c9-EMAIL_CAMPAIGN_2018_08_01_04_38&utm_medium=email&utm_term=0_6e017e2559-e95f1f66c9-48191967"+
"https://portal.tcu.gov.br/biblioteca-digital/governanca-em-tecnologia-de-informacao-e-comunicacao-para-o-setor-publico.htm"+
"http://lelivros.love/book/download-o-caibalion-tres-iniciados-em-epub-mobi-e-pdf/"+
"http://lelivros.love/book/baixar-livro-historia-da-menina-perdida-elena-ferrante-em-pdf-epub-e-mobi-ou-ler-online/"+
"https://blog.github.com/2018-06-29-GIF-that-keeps-on-GIFing/"+
"https://blog.github.com/2018-06-28-archive-project-board-cards/?utm_source=newsletter&utm_medium=email&utm_campaign=july-user-newsletter-2018"+
"https://blog.github.com/2018-07-10-optimizing-open-source-projects-with-github-apps/?utm_source=newsletter&utm_medium=email&utm_campaign=july-user-newsletter-2018"+
"https://brandur.org/minimalism"+
"http://ler-agora.jegueajato.com/"+
"https://news.ycombinator.com/item?id=17675243"+
"https://handshake.org/"+
"https://rain.works/"+
"https://phys.org/news/2018-08-material-unique-behavior-current.html"+
"http://awealthofcommonsense.com/2018/08/the-3-levels-of-wealth/"+
"https://www.workingnomads.co/jobs/react-developer-x-team-21807?utm_source=newsletter&utm_medium=email&utm_campaign=jobalerts32992%2F"+
"http://emboj.embopress.org/content/early/2018/06/06/embj.201899815"+
"https://www.quantamagazine.org/a-math-theory-for-why-people-hallucinate-20180730/"+
"https://spectrum.ieee.org/tech-history/heroic-failures/for-some-reason-these-quantum-mechanics-toys-didnt-catch-on"+
"https://www.fastcompany.com/90212342/3m-knew-your-non-stick-pan-was-poisoning-you-in-the-70s"+
"https://www.youtube.com/user/LeiosOS"+
"https://github.com/graphql-boilerplates/react-fullstack-graphql"+
"https://www.youtube.com/watch?v=qqflFMhkqHM"+
"http://nautil.us/issue/63/horizons/kolmogorov-complexity-and-our-search-for-meaning"+
"https://dweb.me/arc/archive.org/details?"+
"https://codingnest.com/modern-sat-solvers-fast-neat-underused-part-1-of-n/"+
"https://news.ycombinator.com/item?id=17684502"+
"https://hacks.mozilla.org/2018/07/introducing-the-d-web/"+
"https://blog.ungleich.ch/en-us/cms/blog/2018/08/04/mozillas-new-dns-resolution-is-dangerous/"+
"https://www.hackerearth.com/challenges/"+
"https://www.nytimes.com/2018/08/04/business/shrinking-stock-market.html"+
"https://tox.chat/about.html"+
"https://github.com/amitt001/pygmy"+
"http://news.mit.edu/2014/algorithm-recovers-speech-from-vibrations-0804"+
"https://www.wired.com/2017/04/elusive-math-proof-found-almost-lost/"+
"https://blogs.scientificamerican.com/beautiful-minds/the-dark-core-of-personality/"+
"https://www.kaggle.com/kernels"+
"https://archive.nytimes.com/www.nytimes.com/books/first/b/becker-fear.html"+
"https://en.wikipedia.org/wiki/Usenet"+
"https://www.computing.co.uk/ctg/news/3036546/decentralising-the-web-maintaining-the-momentum"+
"https://news.ycombinator.com/item?id=17692005"+
"https://bl.ocks.org/shimizu/e6209de87cdddde38dadbb746feaf3a3"+
"https://bl.ocks.org/mbostock/ad70335eeef6d167bc36fd3c04378048"+
"http://d3indepth.com/force-layout/"+
"https://github.com/tvillarete/apple-music-js"+
"https://github.com/thedaviddias/Front-End-Checklist"+
"https://startingstrength.com/article/exercise_government_style"+
"https://thepolymathproject.com/debra-mashek-interview/"+
"https://thepolymathproject.com/mark-rippetoe/"+
"https://www.youtube.com/watch?v=e_ALAzm7PTc"+
"https://turtleacademy.com/view/programs/54dd661df45859144c3c9869/en"+
"https://github.com/Chalarangelo/30-seconds-of-code"+
"https://github.com/yunity/karrot-frontend"+
"https://github.com/open-source-ideas/open-source-ideas/issues/78"+
"https://sivers.org/slow"+
"https://www.lesswrong.com/posts/ufBYjpi9gK6uvtkh5/for-progress-to-be-by-accumulation-and-not-by-random-walk"+
"http://lostella.github.io/blog/2018/07/25/iterative-methods-done-right"+
"https://www.facebook.com/vjpalm/videos/10153958600148465/UzpfSTY2NzgxODQ2NDpWSzoxMDE1Mzk1ODYwMDE0ODQ2NQ/"+
"https://blog.openai.com/openai-five-benchmark-results/"+
"http://plnkr.co/edit/4sQSQ0ChpJon4OwY2Ag1?p=preview"+
"https://github.com/recoilme/tgram"+
"https://kevq.uk/how-does-mastodon-work/"+
"https://www.reinterpretcast.com/open-hypermedia"+
"https://longreads.com/2018/03/15/welcome-to-the-center-of-the-universe/"+
"https://pudding.cool/2018/08/retraining/"+
"https://www.facebook.com/eurekka.me/photos/a.1801163046780165.1073741828.1767278473501956/1992784177618050/?type=3&theater"+
"https://github.com/luna/luna-studio"+
"https://eji.org/news/study-finds-increased-incarceration-does-not-reduce-crime"+
"https://blog.cryptoaustralia.org.au/2018/08/06/why-you-need-network-wide-ad-blocker-pi-hole/"+
"https://medium.com/@billbuchanan_27654/the-beginning-of-the-end-of-wpa-2-cracking-wpa-2-just-got-a-whole-lot-easier-55d7775a7a5a"+
"https://w3c-ccg.github.io/did-spec/"+
"https://open-source-ideas.github.io/"+
"https://www.youtube.com/watch?v=3lIyDxfUhxM"+
"https://www.washingtonpost.com/amphtml/business/2018/08/06/how-year-old-roads-predict-modern-day-prosperity/"+
"https://ptsjs.org/"+
"https://read.acloud.guru/why-you-cant-effectively-debug-your-modern-systems-with-dashboards-57fe3ecd26bf"+
"http://hackingdistributed.com/2018/08/06/PIEs/"+
"https://www.quantamagazine.org/computer-scientist-constantinos-daskalakis-wins-nevanlinna-prize-20180801/"+
"https://www.wired.com/2008/04/ff-wozniak/"+
"https://blog.mozilla.org/blog/2018/08/07/firefox-offers-recommendations-with-latest-test-pilot-experiment-advance/"+
"https://www.nytimes.com/2018/08/07/technology/snapchat-users.html"+
"https://blog.rescuetime.com/canned-responses-gmail/?utm_source=Blog+Newsletter&utm_campaign=2e69e28347-EMAIL_CAMPAIGN_2018_08_08_03_52&utm_medium=email&utm_term=0_6e017e2559-2e69e28347-48191967"+
"https://www.thecut.com/2018/07/why-you-keep-having-the-same-work-stress-dream-over-and-over.html?utm_source=Blog+Newsletter&utm_campaign=2e69e28347-EMAIL_CAMPAIGN_2018_08_08_03_52&utm_medium=email&utm_term=0_6e017e2559-2e69e28347-48191967"+
"https://hbr.org/2018/07/youre-never-going-to-be-caught-up-at-work-stop-feeling-guilty-about-it?utm_source=Blog+Newsletter&utm_campaign=2e69e28347-EMAIL_CAMPAIGN_2018_08_08_03_52&utm_medium=email&utm_term=0_6e017e2559-2e69e28347-48191967"+
"https://99u.adobe.com/articles/59564/10-ways-to-lead-a-more-fulfilling-creative-career?utm_source=Blog+Newsletter&utm_campaign=2e69e28347-EMAIL_CAMPAIGN_2018_08_08_03_52&utm_medium=email&utm_term=0_6e017e2559-2e69e28347-48191967"+
"https://news.ycombinator.com/item?id=17715839"+
"http://www.cavafy.com/poems/content.asp?id=60"+
"https://gizmodo.uol.com.br/magic-leap-one-pre-venda/"+
"http://www.githunt.com/"+
"https://differentimpulse.com/organic-battery-can-operate-decades/"+
"http://meagan-marie.tumblr.com/post/176788011970/six-months-at-riot-games"+
"https://www.extremetech.com/mobile/275082-qualcomm-unveils-more-powerful-snapdragon-670-chip-for-midrange-phones"+
"https://www.extremetech.com/computing/275102-intel-unveils-new-roadmap-new-14nm-chips-in-2019-10nm-ice-lake-in-2020"+
"https://news.ycombinator.com/item?id=17723104"+
"https://graphql.org/learn/queries/#fragments"+
"https://www.apollographql.com/docs/react/advanced/caching.html#fetchMore"+
"https://tryretool.com/"+
"https://news.ycombinator.com/item?id=17720786"+
"https://newrepublic.com/article/148870/techs-military-dilemma-silicon-valley"+
"https://www.sadiqpk.org/blog/2018/08/08/blogging-with-org-mode.html"+
"https://news.ycombinator.com/item?id=17714815"+
"https://www.lrb.co.uk/v40/n05/jamie-fisher/the-left-handed-kid"+
"https://news.ycombinator.com/item?id=17716098"+
"https://www.facebook.com/story.php?story_fbid=10156413364572778&id=605267777"+
"https://www.theguardian.com/higher-education-network/2018/aug/09/a-phd-should-be-about-improving-society-not-chasing-academic-kudos"+
"http://cbslocal.com/2018/01/18/taking-ancestry-test-makes-buying-life-insurance-harder/"+
"https://www.rmg.co.uk/discover/behind-the-scenes/blog/sex-life-samuel-pepys"+
"https://www.scientificamerican.com/article/how-to-recover-from-romantic-heartbreak/"+
"https://g1.globo.com/ciencia-e-saude/noticia/2018/08/10/o-que-e-o-salto-hidraulico-o-fenomeno-observado-por-da-vinci-que-so-agora-a-ciencia-conseguiu-explicar.ghtml"+
"https://nes.party/"+
"https://www.cs.columbia.edu/~smb/blog/2018-08/2018-08-07.html"+
"https://www.poemhunter.com/poem/under-which-lyre-3/"+
"https://www.nytimes.com/2018/08/08/opinion/oh-the-humanities.html"+
"https://blog.apnic.net/2018/08/09/dns-a-look-back-at-a-look-back/"+
"https://www.samcoope.com/posts/playing_around_with_noise_as_targets"+
"https://dataturks.com/blog/image-moderation-api-comparison.php"+
"https://torrentfreak.com/google-boots-open-source-anti-censorship-tool-from-chrome-store-180810/"+
"https://code.nsa.gov/"+
"https://www.japantimes.co.jp/news/2018/08/08/business/tech/quantum-computing-startup-tries-live-hype/"+
"https://github.com/hasura/graphqurl"+
"https://www.case-podcast.org/20-problem-solving-and-clojure-19-with-rich-hickey"+
"https://www.nytimes.com/2018/08/09/technology/talent-opportunity-gap-pioneer-fund.html"+
"https://drewdevault.com/2018/08/08/Signal.html"+
"https://www.scientificamerican.com/article/end-of-the-rainbow-new-map-scale-is-more-readable-by-people-who-are-color-blind/"+
"https://phys.org/news/2018-08-chemists-blue.html"+
"https://phys.org/news/2018-08-flaw-emergent-gravity.html"+
"https://putanumonit.com/2018/08/09/jobs-inside-the-api/"+
"https://www.sciencedaily.com/releases/2018/08/180809112435.htm"+
"https://betterexplained.com/articles/a-visual-intuitive-guide-to-imaginary-numbers/"+
"https://portswigger.net/blog/practical-web-cache-poisoning"+
"https://www.reuters.com/article/us-cyber-conference/hackers-at-convention-to-ferret-out-election-system-bugs-idUSKBN1KV0ZQ?il=0&utm_medium=Social&utm_source=Twitter"+
"https://arxiv.org/abs/1808.02131"+
"https://ayende.com/blog/184066-C/reading-the-nsas-codebase-lemongraph-review-part-i-storing-nodes"+
"https://www.nybooks.com/daily/2018/07/28/the-ascetic-beauty-of-brancusi/"+
"https://link.springer.com/article/10.1007/s10710-018-9330-7"+
"https://beforetheban.com/"+
"https://www.healio.com/psychiatry/practice-management/news/online/%7B3190207d-0771-45cf-b085-740d048ec110%7D/machine-learning-links-brain-connectivity-patterns-with-psychiatric-symptoms"+
"https://www.osa.org/en-us/about_osa/newsroom/news_releases/2018/researchers_move_closer_to_completely_optical_arti/"+
"http://nautil.us/issue/19/illusions/how-your-brain-decides-without-you"+
"https://jaydaigle.net/blog/teaching/working-backwards/"+
"http://www.leibniz-translations.com/binary.htm"+
"https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Developing_WebExtensions_for_Firefox_for_Android"+
"https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/web-ext_command_reference#web-ext_run"+
"http://www.passportjs.org/"+
"https://blog.github.com/2018-08-09-create-a-13kb-javascript-game-in-30-days-with-js13kgames/"+
"https://www.youtube.com/watch?v=di_eKZ39tN8"+
"https://github.com/mozilla/notes"+
"https://www.google.com/url?q=http://www.escolasapereira.com.br/pagina/1889/&source=gmail&ust=1533905864573000&usg=AFQjCNGivvawssxmaHfdyZ9veDxloxOivQ"+
"https://github.com/eivind88/dankenstein"+
"http://grid.malven.co/"+
"https://www.apollographql.com/docs/react/essentials/local-state.html"+
"https://www.apollographql.com/docs/angular/features/fragments.html#reusing-fragments"+
"https://cors-anywhere.herokuapp.com/"+
"https://ipfs.io/ipfs/QmacAqRVhJX9eS7YJX1vY3ifFKF9CduDqPEgaCUSa4x5xb/"+
"https://medium.com/commitlog/hello-webassembly-882bba5c9fb7"+
"https://www.mortesubitainc.org/"+
"http://kabbalahesoterica.blogspot.com/2017/06/o-caibalion-e-sua-historia.html"+
"http://cosmoseconsciencia.blogspot.com/2016/06/a-roupa-nova-do-caibalion.html"+
"https://www.ybrikman.com/writing/2018/08/12/the-10-to-1-rule-of-writing-and-programming/"+
"https://www.nytimes.com/2007/01/01/us/01charles.html"+
"https://www.nytimes.com/2018/08/11/world/australia/larrimah-mystery.html"+
"https://blog.evjang.com/2018/08/dijkstras.html"+
"http://www.denisdutton.com/jorge_luis_borges_interview.htm"+
"https://www.quantamagazine.org/universal-method-to-sort-complex-information-found-20180813/"+
"https://www.nytimes.com/2018/08/13/magazine/evolution-gene-microbiology.html"+
"https://www.wealthmanagement.com/practice-management/you-can-open-bank"+
"https://www.nasdaq.com/press-release/nvidia-unveils-quadro-rtx-worlds-first-raytracing-gpu-20180813-00977"+
"https://github.com/thepracticaldev/dev.to"+
"https://blog.esciencecenter.nl/why-use-an-fpga-instead-of-a-cpu-or-gpu-b234cd4f309c"+
"https://www.bbc.co.uk/news/technology-45183041"+
"https://en.wikipedia.org/wiki/Absolute_hot"+
"https://www.nytimes.com/2018/08/13/world/europe/erdogan-turkey-lira-crisis.html"+
"https://dev.to/jwoertink/programming-in-the-adult-entertainment-industry-is-broken-hgn"+
"https://news.ycombinator.com/item?id=17756219"+
"http://ovnihoje.com/2018/08/13/evidencias-mostram-que-a-lua-nao-e-o-que-pensamos/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+ovnihoje%2FqOLQ+%28OVNI+Hoje%21%29"+
"https://zeit.co/blog/serverless-docker"+
"https://www.cs.unm.edu/~williams/fpga-ucnc18.pdf"+
"https://www.bloomberg.com/news/features/2018-08-13/how-a-billion-dollar-autonomous-vehicle-startup-lost-its-way"+
"https://www.nature.com/articles/d41586-018-05972-7"+
"https://groups.google.com/a/tensorflow.org/forum/#!topic/announce/qXfsxr2sF-0/discussion"+
"http://www.unboundworlds.com/2018/08/connects-julian-gough-algorithmically-sorted-controlled/?ref=PRH96C06AE639&aid=randohouseinc26226-20&linkid=PRH96C06AE639"+
"http://news.mit.edu/2018/mit-mathematicians-solve-age-old-spaghetti-mystery-0813"+
"https://www.sciencedirect.com/science/article/pii/S1355219817300795"+
"https://news.ycombinator.com/item?id=17752867"+
"https://g1.globo.com/politica/eleicoes/2018/noticia/2018/08/13/tse-recebe-os-registros-de-6-candidatos-a-presidente-prazo-termina-na-quarta-feira.ghtml"+
"https://jrsinclair.com/articles/2018/how-to-deal-with-dirty-side-effects-in-your-pure-functional-javascript/"+
"https://www.neurohacker.com/"+
"https://www.theemergenceproject.org/"+
"http://humansarefree.com/2016/09/russian-scientists-published-this-paper.html"+
"https://adl.io/essays/why-software-development-requires-servant-leaders/"+
"https://sci-hub.tw/https://www.sciencedirect.com/science/article/pii/S1355219809000604?via%3Dihub"+
"https://loopback.io/"+
"http://setosa.io/ev/markov-chains/"+
"http://www.astrosurf.com/lunascan/submittals/sirisena/wall/papers/carlottoRidgeSirisenaMoonV2.pdf"+
"http://www.tsijournals.com/articles/the-mounds-of-cydonia-elegant-geology-or-tetrahedral-geometry-and-reactions-of-pythagoras-and-dirac.html"+
"https://news.ycombinator.com/item?id=17756242"+
"https://futurethinkers.org/daniel-schmachtenberger-generator-functions/"+
"https://civilizationemerging.com/"+
"https://www.edge.org/conversation/j_doyne_farmer-collective-awareness"+
"https://www.youtube.com/watch?v=A8LRxIANzQs"+
"https://www.youtube.com/watch?v=iQnT3bHBAvs&t=6s"+
"https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities"+
"https://eno-lang.org/"+
"https://blog.rescuetime.com/alex-pang-four-day-workweek/?utm_source=Blog+Newsletter&utm_campaign=36d588a65d-EMAIL_CAMPAIGN_2018_08_15_04_24&utm_medium=email&utm_term=0_6e017e2559-36d588a65d-48191967"+
"https://blog.rescuetime.com/growth-mindset-future-of-work/?utm_source=Blog+Newsletter&utm_campaign=36d588a65d-EMAIL_CAMPAIGN_2018_08_15_04_24&utm_medium=email&utm_term=0_6e017e2559-36d588a65d-48191967"+
"https://www.sciencedaily.com/releases/2018/08/180813160528.htm?utm_source=Blog+Newsletter&utm_campaign=36d588a65d-EMAIL_CAMPAIGN_2018_08_15_04_24&utm_medium=email&utm_term=0_6e017e2559-36d588a65d-48191967"+
"https://hbr.org/ideacast/2018/08/networking-myths-dispelled?utm_source=Blog+Newsletter&utm_campaign=36d588a65d-EMAIL_CAMPAIGN_2018_08_15_04_24&utm_medium=email&utm_term=0_6e017e2559-36d588a65d-48191967"+
"https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus"+
"https://zenhabits.net/cats/?utm_source=Blog+Newsletter&utm_campaign=36d588a65d-EMAIL_CAMPAIGN_2018_08_15_04_24&utm_medium=email&utm_term=0_6e017e2559-36d588a65d-48191967"+
"https://www.city-journal.org/html/shays-rebellion-16041.html"+
"https://shanghai.ist/2018/08/16/chinas-first-fully-homegrown-web-browser-found-to-be-google-chrome-clone/"+
"https://www.thedailybeast.com/suicidal-vet-calls-mdma-treatment-a-miracle"+
"https://buzzngo.io/"+
"https://boingboing.net/2018/08/16/who-left-open-the-cookie-jar.html"+
"https://hackernewslater.com/posts/the-hacker-news-habit/"+
"http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0201246"+
"https://www.gq.com/story/the-great-chinese-art-heist"+
"https://jamesclear.com/akrasia"+
"https://matrix.org/blog/home/"+
"https://chr15m.github.io/on-self-hosting-and-decentralized-software.html"+
"https://chr15m.github.io/dirc/#hn"+
"https://changelog.com/jsparty/38"+
"https://www.apollographql.com/docs/resources/graphql-glossary.html"+
"https://graphqlmastery.com/blog/graphql-security-in-node-js-project"+
"https://medium.freecodecamp.org/a-5-line-major-efficiency-hack-for-your-graphql-api-type-resolvers-b58438b62864"+
"https://pt.wikipedia.org/wiki/Memex"+
"https://gizmodo.uol.com.br/cheiro-de-coisas-que-nao-existem-odores-fantasmas/"+
"http://natecull.org/wordpress/2017/06/26/dataspace-0/"+
"https://www.quantamagazine.org/functional-fingerprint-may-identify-brains-over-a-lifetime-20180816/"+
"https://news.ycombinator.com/"+
"https://www.extremetech.com/extreme/275852-mit-develops-water-to-air-wireless-communication"+
"https://chr15m.github.io/hash-function-attacks-illustrated.html"+
"http://www.sciencemag.org/news/2018/08/researcher-center-epic-fraud-remains-enigma-those-who-exposed-him"+
"http://www.lambdashell.com/"+
"https://daveceddia.com/context-api-vs-redux/"+
"https://news.ycombinator.com/item?id=17788140"+
"https://www.extremetech.com/extreme/275935-physicists-may-have-detected-the-remains-of-black-holes-from-another-universe"+
"https://dolardev.com/guia-definitivo-para-receber-em-dolares-programando-de-casa/"+
"https://jamesclear.com/implementation-intentions"+
"https://maxhallinan.com/posts/2018/08/17/the-usefulness-of-abstracting-over-time/"+
"https://gizmodo.uol.com.br/primeiras-informacoes-sarcofago-amaldicoado-egito/"+
"https://freshjobs.io/"+
"https://people.csail.mit.edu/jshun/6886-s18/"+
"https://hackernoon.com/getting-deep-into-evm-how-ethereum-works-backstage-ac7efa1f0015"+
"http://natecull.org/wordpress/2017/07/05/dataspace-1/"+
"https://litepaper.com/resources/intro-to-augur"+
"https://techcrunch.com/2018/08/18/distributed-teams-are-rewriting-the-rules-of-officeless-politics/"+
"https://blog.mollie.com/how-we-hacked-our-office-doorbell-using-slack-messagebird-and-now-b2042c060e29"+
"https://www.bloomberg.com/news/features/2018-08-16/billionaires-and-the-guru-how-an-indian-family-lost-2-billion"+
"https://github.com/mb-14/gomarkov/tree/master/examples/fakernews"+
"https://medium.com/@kaistinchcombe/decentralized-and-trustless-crypto-paradise-is-actually-a-medieval-hellhole-c1ca122efdec"+
"https://www.extremetech.com/extreme/275643-stanford-researchers-build-ai-directly-into-camera-optics"+
"https://openai.com/five/"+
"https://www.youtube.com/watch?v=S1OwOd-war8"+
"https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989"+
"https://gizmodo.uol.com.br/arm-notebooks-cortex-a76-deimos-hercules/"+
"https://gizmodo.uol.com.br/ia-online-texto-para-imagens/"+
"https://gizmodo.uol.com.br/brasil-segundo-mercado-uber-mundo/"+
"http://cloudingmine.com/idempotence-what-is-it-and-why-should-i-care/"+
"https://a16z.com/2018/08/17/service-as-a-sku/"+
"https://brokenco.de/2018/08/15/five-stages-of-yaml.html"+
"https://mdxjs.com/"+
"http://www.thoriumenergyworld.com/press-release/china-invests-big-in-clean-and-cheap-energy-from-thorium"+
"https://harpers.org/archive/2012/01/stop-payment-a-homeowners-revolt-against-the-banks/"+
"https://www.theatlantic.com/science/archive/2018/08/parasite-vine-wasp-tumor/567823/?single_page=true"+
"https://slate.com/culture/2018/08/reader-come-home-by-maryanne-wolf-reviewed.html"+
"https://www.nytimes.com/2016/03/20/magazine/the-secrets-of-the-wave-pilots.html"+
"https://zen-of-programming.com/design/"+
"https://github.com/diogoalves"+
"https://www.bbc.com/portuguese/geral-39483587"+
"https://medium.com/the-polymath-project/loneliness-is-not-about-being-alone-343d2be67643"+
"https://www.amazon.com/After-Buddhism-Rethinking-Dharma-Secular-ebook/dp/B0155072XM/ref=as_li_ss_tl?ie=UTF8&qid=1534649040&sr=8-1&keywords=after+buddhism&linkCode=sl1&tag=mmeditations-20&linkId=f379b5c80bd7896400b99e2506181054&language=en_US"+
"https://thepolymathproject.com/stephen-asma-why-we-need-religion/"+
"https://gizmodo.uol.com.br/produtora-video-porno-personalizar-deepfake/"+
"https://twitter.com/mmeditations/status/1030704404800843776"+
"https://checklyhq.com/blog/2018/08/creating-a-chrome-extension-in-2018-the-good-the-bad-and-the-meh/"+
"http://2ality.com/2018/08/enums-via-proxies.html"+
"https://mobiforge.com/design-development/the-generic-sensor-api"+
"https://github.com/sinclairtarget/um"+
"https://www.learnopencv.com/why-does-opencv-use-bgr-color-format/"+
"https://hothardware.com/news/qualcomm-samples-7nm-next-gen-snapdragon-soc"+
"https://gizmodo.uol.com.br/netflix-sistema-pagamento-se-livrar-apple/"+
"https://gizmodo.uol.com.br/gmail-android-cancelar-envio/"+
"https://www.facebook.com/EgoStupriAmoreMaps/photos/a.725151950861889/1986607398049665/?type=3&theater"+
"https://www.dwavesys.com/press-releases/d-wave-breakthrough-demonstrates-first-large-scale-quantum-simulation-topological"+
"https://phys.org/news/2018-08-depression-seafloor-whales-prospective-sites.html"+
"https://www.economist.com/open-future/2018/06/29/bullshit-jobs-and-the-yoke-of-managerial-feudalism"+
"https://outraspalavras.net/capa/a-estranha-sociedade-dos-empregos-de-merda/"+
"https://medium.com/@hugo.oliveira.rocha/what-they-dont-tell-you-about-event-sourcing-6afc23c69e9a"+
"https://www.masswerk.at/nowgobang/2018/observing-minard"+
"https://news.ycombinator.com/item?id=17817375"+
"https://www.extremetech.com/extreme/275768-artificial-general-intelligence-is-here-and-impala-is-its-name"+
"https://www.livescience.com/63384-black-sarcophagus-alexandria-inscriptions.html"+
"https://blog.rescuetime.com/coworkers-collaborate/?utm_source=Blog+Newsletter&utm_campaign=0a23214f24-EMAIL_CAMPAIGN_2018_08_22_04_41&utm_medium=email&utm_term=0_6e017e2559-0a23214f24-48191967"+
"https://www.nytimes.com/2018/08/21/smarter-living/work-desk-improvements-office.html?utm_source=Blog+Newsletter&utm_campaign=0a23214f24-EMAIL_CAMPAIGN_2018_08_22_04_41&utm_medium=email&utm_term=0_6e017e2559-0a23214f24-48191967"+
"https://99u.adobe.com/articles/59532/does-your-company-need-a-chief-storyteller?utm_source=Blog+Newsletter&utm_campaign=0a23214f24-EMAIL_CAMPAIGN_2018_08_22_04_41&utm_medium=email&utm_term=0_6e017e2559-0a23214f24-48191967"+
"https://www.nature.com/articles/d41586-018-06004-0"+
"https://blog.rescuetime.com/long-tail-time-managment/?utm_source=Blog+Newsletter&utm_campaign=0a23214f24-EMAIL_CAMPAIGN_2018_08_22_04_41&utm_medium=email&utm_term=0_6e017e2559-0a23214f24-48191967"+
"https://blogs.scientificamerican.com/cross-check/a-buddhism-critic-goes-on-a-silent-buddhist-retreat/"+
"https://www.technologyreview.com/s/611816/the-simple-but-ingenious-system-taiwan-uses-to-crowdsource-its-laws/"+
"https://medium.com/swlh/why-high-performers-dont-use-to-do-lists-5d298045444d"+
"https://public-inbox.org/git/20180725083024.16131-1-avarab@gmail.com/"+
"https://www.newstatesman.com/culture/books/2012/09/your-brain-pseudoscience-rise-popular-neurobollocks"+
"https://news.ycombinator.com/item?id=17817627"+
"https://johnhw.github.io/umap_primes/index.md.html"+
"https://www.blinkingcaret.com/2018/08/22/software-development-emergent-system-ndepend/"+
"https://towardsdatascience.com/introduction-to-markov-chains-50da3645a50d"+
"https://github.com/mb-14/gomarkov"+
"https://www.youtube.com/watch?v=QbUPfMXXQIY"+
"https://www.youtube.com/watch?v=nq6iPZVUxZU"+
"https://www.youtube.com/watch?v=UJICwHNb4BQ"+
"https://chrome.google.com/webstore/detail/puppeteer-recorder/djeegiggegleadkkbgopoonhjimgehda"+
"https://a9t9.com/kantu/docs/visual-ui-testing"+
"https://dejanseo.com.au/competitor-hack/"+
"https://github.com/TadasBaltrusaitis/OpenFace"+
"https://nordicapis.com/20-emotion-recognition-apis-that-will-leave-you-impressed-and-concerned/"+
"https://sirupsen.com/read/"+
"https://hacks.mozilla.org/2017/06/introducing-filterbubbler-a-webextension-built-using-reactredux/"+
"https://www.filterbubbler.org/"+
"https://www.nature.com/articles/s41598-018-30619-y"+
"https://vimeo.com/146340483"+
"https://home.cern/about/updates/2018/08/alpha-experiment-takes-antimatter-new-level"+
"https://www.nytimes.com/2018/08/23/opinion/international-world/the-bitter-regrets-of-a-useless-chinese-daughter.html"+
"https://www.youtube.com/watch?v=5aE29fiatQ0"+
"https://honest.engineering/posts/why-use-graphql-good-and-bad-reasons"+
"https://phys.org/news/2018-08-team-evidence-matter-matter-coupling.html"+
"https://www.nature.com/articles/d41586-018-05979-0"+
"https://thebaffler.com/salvos/privatizing-poverty-phillips-fein"+
"http://felleisen.org/matthias/OnHtDP/index.html"+
"https://www.process.st/best-productivity-apps/"+
"https://www.youtube.com/watch?v=n_roBMt08jE&feature=youtu.be"+
"https://www.prisma.io/blog/performance-release-aeduv0rei0ji/"+
"https://medium.com/open-graphql/apollo-multiple-clients-with-react-b34b571210a5"+
"https://tomasalabes.me/blog/graphql/node/microservices/2018/08/11/graphql-architectures.html"+
"https://www.prisma.io/blog/performance-engineering-aeduv0rei0jk/"+
"https://www.youtube.com/watch?v=F_M8v6MK0Sc"+
"https://www.reuters.com/article/us-worldbank-cba-blockchain/world-bank-launches-world-first-blockchain-bond-idUSKCN1L80DP"+
"http://en.businesstimes.cn/articles/102229/20180824/chinese-internet-and-the-true-worth-of-china-s-big-three%E2%80%94alibaba-baidu-and-tencent.htm"+
"https://threejs.org/"+
"https://github.com/vasturiano/3d-force-graph"+
"https://blog.npmjs.org/post/177279385225/three-new-features-to-help-our-users-protect"+
"https://tech.firstlook.media/keylist-rfc-explainer"+
"https://blog.ghost.org/2-0/"+
"https://news.ycombinator.com/item?id=17830235"+
"https://css-tricks.com/level-up-your-filter-game/"+
"https://oprea.rocks/blog/what-do-the-three-dots-mean-in-javascript/"+
"https://www.briangilham.com/be-kind"+
"https://twitter.com/atomicthumbs/status/1032939617404645376"+
"https://resobscura.blogspot.com/2018/08/opium-or-cucumber-debunking-myth-about.html"+
"https://bl.ocks.org/vasturiano"+
"https://www.extremetech.com/computing/276169-amd-moves-all-7nm-cpu-gpu-production-to-tsmc"+
"https://80000hours.org/2017/11/consider-applying-for-a-phd-program-now/"+
"https://thegradient.pub/beyond-the-pixel-plane-sensing-and-learning-in-3d/"+
"https://edition.cnn.com/interactive/2018/08/world/great-barrier-reef/"+
"https://babeljs.io/blog/2018/08/27/7.0.0"+
"https://news.ycombinator.com/item?id=17854065"+
"https://github.com/ornicar/lila"+
"https://blog.okmeter.io/real-world-ssd-wearout-a3396a35c663"+
"https://swellandcut.com/2018/08/15/the-tyranny-of-the-perfect-day/"+
"https://hbr.org/2018/08/what-data-scientists-really-do-according-to-35-data-scientists"+
"https://blogs.scientificamerican.com/cross-check/the-paradox-of-karl-popper/"+
"https://www.collaborativefund.com/blog/expiring-vs-lt-knowledge/"+
"https://aeon.co/essays/hume-is-the-amiable-modest-generous-philosopher-we-need-today"+
"http://slatestarcodex.com/2015/12/24/how-bad-are-things/"+
"https://github.com/parcel-bundler/parcel"+
"https://github.com/dequelabs/axe-core"+
"https://twitter.com/atomicthumbs"+
"https://webtorrent.io/docs"+
"https://www.youtube.com/watch?v=kxHRATfvnlw"+
"https://speakerdeck.com/feross/webrtc-everywhere-beyond-the-browser-at-data-terra-nemo-2015"+
"https://www.businessinsider.com/sinister-hunger-stones-dire-warnings-surfaced-europe-2018-8"+
"https://www.citusdata.com/blog/2018/08/29/datatypes-you-should-consider-using/"+
"https://www.youtube.com/watch?v=MX_207fKkaU"+
"http://www.clubedotaro.com.br/site/r64_2_arv_vida.asp"+
"https://github.com/alexeisavca/webtorrentapp"+
"https://ronsoros.github.io/"+
"https://webtorrent.io/faq"+
"https://github.com/ronsoros/ronsoros.github.io/blob/master/index.html"+
"https://github.com/andreapaiola/P2P-CDN"+
"https://files.fm/"+
"https://diegorbaquero.github.io/PeerFast/#"+
"https://btorrent.xyz/"+
"https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server"+
"https://exame.abril.com.br/economia/nao-e-educacao-que-torna-dinamarca-igualitaria-diz-estudo/"+
"https://javascript.tumblr.com/post/177492037092/making-a-progressive-web-app-with-webpack-just-got"+
"https://blog.sourcerer.io/why-is-a-java-guy-so-excited-about-node-js-and-javascript-7cfc423efb44"+
"https://rirparanaomorrer.blogfolha.uol.com.br/2018/08/30/prem-baba-e-a-perversidade-do-predador-em-pele-de-curandeiro%e2%80%a8/"+
"https://extra.globo.com/famosos/filho-de-edmundo-dispara-homens-deveriam-discutir-abandono-nao-aborto-23022219.html?utm_source=Facebook&utm_medium=Social&utm_campaign=Extra"+
"https://brasil.elpais.com/brasil/2018/08/29/cultura/1535549387_295932.html?id_externo_rsoc=FB_BR_CM"+
"http://squidl.ink/"+
"https://filemap.xyz/"+
"https://tcloud-lunik.herokuapp.com/"+
"https://www.bitchute.com/"+
"https://xuset.github.io/planktos/"+
"https://github.com/Lunik/tcloud"+
"https://cinetimes.org/"+
"https://bitlove.org/"+
"https://tnoevry.github.io/wwt/"+
"https://peerify.btorrent.xyz/"+
"https://github.com/FaCuZ/torrentmedia"+
"http://cinematrix.one/"+
"https://peertube.cpy.re/"+
"http://twister.net.co/?p=589"+
"https://github.com/pldubouilh/webtorrent-webui"+
"https://github.com/cdnbye/hlsjs-p2p-engine"+
"https://www.hongkiat.com/blog/100-useful-bookmarklets-for-better-productivity-ultimate-list/"+
"https://github.com/novage/p2p-media-loader"+
"https://cheff.cuadranteweb.com/sync/"+
"https://thenewstack.io/whats-coming-up-in-javascript-2018-async-generators-better-regex/"+
"https://www.qualitydigest.com/inside/statistics-column/010416-statistical-tolerance-intervals.html#"+
"https://www.telerik.com/campaigns/kendo-ui/wp-functional-programming-with-js-cheat-sheet?utm_medium=cpm&utm_source=jsweekly&utm_campaign=kendo-ui-jquery-whitepaper-funcwithjs&utm_content=primary"+
"https://hackernoon.com/gradient-descent-aynk-7cbe95a778da"+
"https://aralroca.com/2018/08/24/first-steps-with-tensorflow-js/"+
"https://www.robinwieruch.de/graphql-apollo-server-tutorial/"+
"https://pusher.com/tutorials/live-graph-d3"+
"file:///C:/Users/diogo.alves/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/85CC3HVP/ValorAdicionado.pdf"+
"https://i.blackhat.com/us-18/Thu-August-9/us-18-Lukasiewicz-WebAssembly-A-New-World-of-Native_Exploits-On-The-Web-wp.pdf"+
"https://github.com/ITPNYU/ICM-2018"+
"https://github.com/ITPNYU/ICMadness-2018"+
"https://desktop.github.com/"+
"https://code.fb.com/ai-research/facebook-and-nyu-school-of-medicine-launch-research-collaboration-to-improve-mri/?utm_source=email&utm_medium=fb4d-newsletter-august&utm_campaign=organic&utm_offering=artificial-intelligence&utm_product=artificial-intelligence&utm_content=body-research-collaboration&utm_location=5-research-collaboration&mkt_tok=eyJpIjoiTjJWbE1EWTJPR1ZtTVdObSIsInQiOiJ3VEc2ZHpHWE9LQmpNQnJUUGtlU0pJVUZJVGVSNExVNWo1ZzZDZnJUZTNmbGhpNmhCb0RESWpzT1B2V1ppT3BEa1Q0UnV0dnpkZUl0MUN3U2JvamFKV24wZnFmNU5hUkh5bkkyRG1aTjZ3UkNhYm1DczBoQ2VpVHcrcmtERW1ZbSJ9"+
"https://medium.com/apache-mxnet/onnx-model-zoo-developing-a-face-recognition-application-with-onnx-models-64eeeddb9c7a?mkt_tok=eyJpIjoiTjJWbE1EWTJPR1ZtTVdObSIsInQiOiJ3VEc2ZHpHWE9LQmpNQnJUUGtlU0pJVUZJVGVSNExVNWo1ZzZDZnJUZTNmbGhpNmhCb0RESWpzT1B2V1ppT3BEa1Q0UnV0dnpkZUl0MUN3U2JvamFKV24wZnFmNU5hUkh5bkkyRG1aTjZ3UkNhYm1DczBoQ2VpVHcrcmtERW1ZbSJ9"+
"https://pickyassist.com/"+
"https://bitbucket.org/liamilan/wolfram-cellular-automata"+
"https://news.ycombinator.com/item?id=17871313"+
"https://blog.rescuetime.com/honest-job-description/?utm_source=Blog+Newsletter&utm_campaign=1d4fe2f360-EMAIL_CAMPAIGN_2018_08_29_03_24&utm_medium=email&utm_term=0_6e017e2559-1d4fe2f360-48191967"+
"https://jamesclear.com/stay-focused?utm_source=Blog+Newsletter&utm_campaign=1d4fe2f360-EMAIL_CAMPAIGN_2018_08_29_03_24&utm_medium=email&utm_term=0_6e017e2559-1d4fe2f360-48191967"+
"https://sloanreview.mit.edu/article/the-challenge-of-scaling-soft-skills/?utm_source=Blog+Newsletter&utm_campaign=1d4fe2f360-EMAIL_CAMPAIGN_2018_08_29_03_24&utm_medium=email&utm_term=0_6e017e2559-1d4fe2f360-48191967"+
"https://hbr.org/2018/08/how-to-email-someone-you-havent-talked-to-in-forever?utm_source=Blog+Newsletter&utm_campaign=1d4fe2f360-EMAIL_CAMPAIGN_2018_08_29_03_24&utm_medium=email&utm_term=0_6e017e2559-1d4fe2f360-48191967"+
"https://hackernoon.com/building-trending-activity-feeds-using-graphql-and-neo4j-e62ee790238e"+
"https://github.com/copy/v86"+
"https://www.youtube.com/watch?v=SySdchiCjsQ"+
"https://www.youtube.com/watch?v=h0sfFX7WH1c"+
"https://github.com/fastlane/fastlane"+
"https://github.com/protocolbuffers/protobuf"+
"https://github.com/mweststrate/immer"+
"https://github.com/ant-design/ant-design"+
"https://github.com/swaywm/sway"+
"https://github.com/chr15m/simple-peer-test"+
"https://github.com/feross/simple-peer"+
"https://github.com/rawrtc/rawrtc-terminal-demo"+
"https://medium.com/the-polymath-project/a-few-principles-for-thinking-clearly-d18a74a2ebe9"+
"https://twitter.com/mmeditations/status/1035472981269479431"+
"https://www.lesswrong.com/posts/4Bwr6s9dofvqPWakn/science-as-attire"+
"http://tools-for-thought.com/2008/03/03/distributed-cognition/"+
"https://www.youtube.com/watch?v=jey_CzIOfYE"+
"http://www.michaelnygard.com/blog/2018/01/coherence-penalty-for-humans/"+
"http://book.bionumbers.org/"+
"https://feediary.com/"+
"https://workorder.io/"+
"https://www.cs.tau.ac.il/~tromer/synesthesia/"+
"https://g1.globo.com/bemestar/noticia/2018/09/03/campanha-de-vacinacao-contra-polio-e-sarampo-e-prorrogada-ate-14-de-setembro.ghtml"+
"https://medium.com/the-polymath-project/a-few-principles-for-intellectual-freedom-c1bb5614fa4c"+
"https://blog.rescuetime.com/most-satisfying-jobs/?utm_source=Blog+Newsletter&utm_campaign=1d4fe2f360-EMAIL_CAMPAIGN_2018_08_29_03_24&utm_medium=email&utm_term=0_6e017e2559-1d4fe2f360-48191967"+
"https://beta.observablehq.com/"+
"https://hackaday.com/2017/12/28/34c3-hacking-into-a-cpus-microcode/"+
"https://gizmodo.uol.com.br/idec-portas-interativas-linha-4-sp-protecao-dados/"+
"https://tinyletter.com/jamesbowman/letters/upduino-a-9-99-fpga"+
"http://archagon.net/blog/2018/09/03/good-spirits-persisting-data-statelessly/"+
"https://www.washingtonpost.com/national/health-science/lab-grown-brain-bits-open-windows-to-the-mind--and-a-maze-of-ethical-dilemmas/2018/09/02/9a76efee-a25b-11e8-83d2-70203b8d7b44_story.html?utm_term=.38969371d19f"+
"https://blogs.wsj.com/cio/2018/08/31/silicon-valley-myths-aside-time-is-on-the-side-of-aging-entrepreneurs/"+
"https://spectrum.ieee.org/view-from-the-valley/at-work/tech-careers/desperate-for-data-scientists"+
"https://www.youtube.com/watch?v=iEphZNlQ6bk"+
"https://steveblank.com/2018/09/05/is-the-lean-startup-dead/"+
"https://news.ycombinator.com/item?id=17917479"+
"https://people.eecs.berkeley.edu/~rcs/research/interactive_latency.html"+
"https://blog.rescuetime.com/how-to-make-a-schedule/?utm_source=Blog+Newsletter&utm_campaign=808cfd5dd7-EMAIL_CAMPAIGN_2018_09_04_05_02&utm_medium=email&utm_term=0_6e017e2559-808cfd5dd7-48191967"+
"https://blog.rescuetime.com/rescuetime-work-hours/?utm_source=Blog+Newsletter&utm_campaign=808cfd5dd7-EMAIL_CAMPAIGN_2018_09_04_05_02&utm_medium=email&utm_term=0_6e017e2559-808cfd5dd7-48191967"+
"https://medium.com/thrive-global/heres-how-successful-people-avoid-information-overwhelm-f32d3e939801"+
"https://hbr.org/2018/09/to-cope-with-stress-try-learning-something-new?utm_source=Blog+Newsletter&utm_campaign=808cfd5dd7-EMAIL_CAMPAIGN_2018_09_04_05_02&utm_medium=email&utm_term=0_6e017e2559-808cfd5dd7-48191967"+
"https://fs.blog/2018/09/decision-matrix/?utm_source=Blog+Newsletter&utm_campaign=808cfd5dd7-EMAIL_CAMPAIGN_2018_09_04_05_02&utm_medium=email&utm_term=0_6e017e2559-808cfd5dd7-48191967"+
"https://www.freeletics.com/pt/blog/posts/10-atalhos-para-aproveitar-ao-maximo-as-suas-24-horas/?noredirect=pt_PT&CID=_CRM_NL20180906TenProductivityHacks_0&utm_medium=NL&utm_source=newsletter&utm_campaign=NL201809065TenProductivityHacks"+
"https://thehustle.co/the-man-who-won-the-lottery-14-times"+
"https://www.historytoday.com/james-waterson/who-were-mamluks"+
"https://exist.io/static/feature_dashboard.html"+
"https://www.youtube.com/watch?v=MxU_AJCqVWc&t=20s"+
"http://danml.com/"+
"http://m.nautil.us/issue/64/the-unseen/the-ethics-of-consciousness-hunting"+
"https://news.ycombinator.com/item?id=17924798"+
"http://armazemmemoria.com.br/quem-somos/"+
"https://www.sitepoint.com/using-fourier-transforms-web-audio-api/"+
"https://www.sigidwiki.com/wiki/JT65"+
"https://www.zoom.com.br/impressora-e-multifuncional/impressora-brother-hl-1212w-laser-preto-e-branco-sem-fio"+
"https://www.extremetech.com/extreme/276614-japans-aterui-ii-is-the-fastest-supercomputer-dedicated-to-astronomy-research"+
"https://www.npr.org/sections/health-shots/2018/09/09/645629133/infectious-theory-of-alzheimers-disease-draws-fresh-interest"+
"https://github.com/erikbrinkman/d3-dag"+
"https://mathiasbynens.be/notes/es-unicode-property-escapes"+
"http://2ality.com/2017/07/regexp-unicode-property-escapes.html"+
"https://mathiasbynens.be/notes/javascript-unicode"+
"https://github.com/wilkerlucio/huffman_js"+
"https://www.npmjs.com/package/compressjs"+
"https://github.com/antirez/smaz/blob/master/smaz.c"+
"https://github.com/personalcomputer/smaz.js?utm_source=recordnotfound.com"+
"https://mathiasbynens.be/notes/javascript-escapes";

export default links;